### ISSUE TITLE
Obtain free (free) beats and experiment with timing

### ISSUE THREAD

**Issue by icburns** [httpNick/AlexaBestMC#13]
We'll want a few tracks to choose from with a decent range in bmp to allow for different verse structures. Ideally, the audio files will be chopped into up to 5 pieces as separators and intro/outro.

**Comment by icburns** [comment]
This is a bit of an unconventional reporting method, but check it, yo
http://plnkr.co/edit/mTv35pSJzFFzHeFx1dXF?p=preview

**Comment by icburns** [comment]
I'm still on the prowl for more decent free and unlicensed beats (youtube can be a bit of a grey area, so I'm working with explicitly stated unrestricted use), but Alexa seems pretty consistent at 5 syllables per second. After applying some mathematics, that figures to 1200/bpm syllables per measure (this is assuming the industry standard 4/4 time).

Check my work for Concrete Jungle:
100 beats/minute / 60 seconds/minute = 10/6 b/s
5 syllables/second / 10/6 b/s = 3 syllables/beat
3 sy/b * 4 beats/measure = 12 syllables per measure

**Comment by icburns** [comment]
My next step is to start slicing these tracks up into bite size pieces that we can serve before, after and between MC Alexa's rhymes with SSML audio tags.

**Comment by httpNick** [comment]
sounds good Ian, so in the repeat-back speech of Alexa you use tags to specify chunks of audio to play?

**Comment by icburns** [comment]
Exactly. It's interjecting a <audio src="" /> tag in the response text.

**Comment by icburns** [comment]
There is now a verseConverter which accepts an array of verses and returns output formatted as a string of lines and in ssml. This ssml should be setting the output and the type should be 'ssml'
