### ISSUE TITLE
[Delivery] - Spike: Music to play along with voice

### ISSUE THREAD

**Issue by httpNick** [httpNick/AlexaBestMC#3]
If it is possible, can we sync the voice with music/beat?

**Comment by icburns** [comment]
In short, no. That said, we can add up to 5 snippets of audio between lines. It may look something like this:
<audio>intro</audio>
<line />
<audio>beat/hit</audio>
<line />
<audio>beat/hit</audio>
<line />
<audio>beat/hit</audio>
<line />
<audio>outro</audio>
